services:
  db:
    container_name: bookstore
    image: postgres
    environment:
      POSTGRES_USER: side
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres/bookstore
      POSTGRES_DB: bookstore
    volumes:
      - db:/data/postgres/bookstore
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: